# Generated by Django 6.0.2 on 2026-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_nutritionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='grams',
            field=models.IntegerField(default=100),
        ),
    ]
