# Generated by Django 6.0.2 on 2026-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionitem',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionitem',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionitem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionitem',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
